server:
  error:
    include-stacktrace: on-param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aeroporto?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update